{% set name = "htmlgen" %}
{% set org = "srittau" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ org }}/python-{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 891ac5a30266d658a6d4e708e53f1c4a0621a36cbdbda4c4c4e9ac09a06ea863

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry-core >=1.0.0
  run:
    - python >={{ python_min }}

test:
  requires:
    - pip
    - python {{ python_min }}
  imports:
    - {{ name }}
  commands:
    - pip check

about:
  home: https://github.com/srittau/python-htmlgen
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Library to generate HTML from classes.
  description: Library to generate HTML from classes.
  doc_url: https://github.com/srittau/python-htmlgen
  dev_url: https://github.com/srittau/python-htmlgen

extra:
  recipe-maintainers:
    - tdegeus
